<?php
define('MIGRATE_RSVP_DATABASE_NAME', variable_get('migrate_rsvp_database', 'rsvp'));
define('MIGRATE_RSVP_FILES_DIRECTORY', variable_get('migrate_rsvp_file_path', '/var/www/html/rsvp/'));

/**
 * Implementation of hook_menu().
 */
function migrate_rsvp_menu() {
  $items = array();
  
  $items['admin/config/development/migrate_rsvp'] = array(
    'title' => 'RSVP Migration Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('migrate_rsvp_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
  );
  
  return $items;
}

/**
 * Form to setting up the database name and migration file path for migration of data.
 */
function migrate_rsvp_settings($form, &$form_state) {
  $form['migrate_rsvp_database'] = array(
    '#type' => 'textfield',
    '#title' => 'Database name',
    '#default_value' => variable_get('migrate_rsvp_database', 'rsvp'),
    '#description' => t('Please enter the name of the database.  Note that the database must be accessible by current website db user and must reside on the same db server.'),
    '#required' => TRUE,
  );
  
  $form['migrate_rsvp_file_path'] = array(
    '#type' => 'textfield',
    '#title' => 'Migrated Files Path',
    '#default_value' => variable_get('migrate_rsvp_file_path', '/var/www/html/rsvp/media/files'),
    '#description' => t('Please enter the full path to get to the home directory of the migrating site - the files will be found through the base'),
    '#required' => TRUE,
  );
  
  return system_settings_form($form);
}
