<?php
/**
 * Implements hook_permisson().
 */
function play_web_permission() {
  $permissions['administer play_web settings'] = array(
    'title' => t('Administer play_web settings.'),
    'restrict access' => TRUE,
  );
  return $permissions;
}
function play_web_help($path, $arg) {
  if ($path == 'admin/help#play_web') {
    return t('Módulo para configuración de play_web');
  }
}
/**
 * Implements hook_menu().
 */
function play_web_menu() {
  $items=array();
  
  $items['admin/config/system/play_web'] = array(
    'title'            => t('play_web settings'),
    'description'      => t('Configure settings for play_web'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('play_web_admin_settings_form'),
    'access arguments' => array('administer play_web settings'),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'play_web.admin.inc',
  );
  return $items;
}

function play_web_init(){
  // check if admin or moderator
  if(user_access('administer')) {
    return;
  }
  $statusplay_web=variable_get('play_web_status',FALSE);
  if(arg(0)=='node' && $statusplay_web){
    $node=node_load(arg(1));
    if($node->type=='article'){
      $wrapperplay_web=variable_get('play_web_wrapper','play_web-wrapper');
      $debugModeplay_web=variable_get('play_web_debug',FALSE);
      if($debugModeplay_web){
        //Debug mode
        $footerJS='var zflag_parent="'.$wrapperplay_web.'";
var zflag_nid="2264";
var zflag_cid="1534";
var zflag_sid="0";
var zflag_sz="85";
var zflag_vast_domain="http://xp1.play_web.com/";
var zflag_width="1";
var zflag_height="1";';
        drupal_add_js($footerJS, array('type' => 'inline', 'scope' => 'footer', 'weight' => 98));
        drupal_add_js('http://c1.play_web.com/jsc/c1/frd.js', array('type' => 'external', 'scope' => 'footer', 'weight' => 99));
      }else{
        $footerJS='var zflag_parent="'.$wrapperplay_web.'";
var zflag_nid="2870";
var zflag_cid="1";
var zflag_sid="1";
var zflag_sz="85";
var zflag_vast_domain="http://xp1.play_web.com/";
var zflag_width="1";
var zflag_height="1";
var zflag_bchan="2";';
        drupal_add_js($footerJS, array('type' => 'inline', 'scope' => 'footer', 'weight' => 98));
        drupal_add_js('http://e2.play_web.com/jsc/e2/frd.js', array('type' => 'external', 'scope' => 'footer', 'weight' => 99));
      }
      drupal_add_css(drupal_get_path('module', 'play_web').'/play_web.css');
    }
  }
}
