<?php
/**
 * @file
 * Installation file for Play Web Integration.
 */

/**
 * Implements hook_install().
 */
function play_web_install() {
  variable_set('play_web_status',FALSE);
  variable_set('play_web_debug',FALSE);
  variable_set('play_web_wrapper','play-web');
}

/**
 * Implements hook_uninstall().
 */
function play_web_uninstall() {
  #Delete all variables
  variable_del('play_web_status');
  variable_del('play_web_debug');
  variable_del('play_web_wrapper');
}
