<?php
/**
 * @file
 * Installation file for Google Analytics module.
 */

/**
 * Implements hook_install().
 */
function imagebrowser_legacy_install() {
  variable_set('imagebrowser_legacy_status',FALSE);
  variable_set('imagebrowser_legacy_stylename','');
}

/**
 * Implements hook_uninstall().
 */
function imagebrowser_legacy_uninstall() {
  #Delete all variables
  variable_del('imagebrowser_legacy_status');
  variable_del('imagebrowser_legacy_stylename');
}
