<?php

function imx_image_labels_alter_field_widget_form_alter(&$element, &$form_state, $context){
  if ($context['field']['type'] == 'image') {
    foreach (element_children($element) as $key => $child) {
      $element[$key]['#process'][] = 'imx_image_labels_alter_field_widget_process';
    }
  }
}

function imx_image_labels_alter_field_widget_process($element, &$form_state, $form){
  if(isset($element['alt'])){
    $element['alt']['#title']       = t('Caption | Description');
    $element['alt']['#required']    = TRUE;
    $element['alt']['#description'] = t('A caption or description for this image. This value might be used for SEO or other widgets and cannot be higher than 500 characters.');
  }
  if(isset($element['title'])){
    $element['title']['#required']    = TRUE;
    $element['title']['#title']       = t('Authoring | Copyright');
    $element['title']['#description'] = t('The authoring or copyright for this image. This value might be used for SEO or other widgets and can not be higher than 500 characters. Default value <em>Especial</em>');
    if(!isset($element['title']['#default_value']) || empty($element['title']['#default_value'])){
      $element['title']['#default_value'] = 'Especial';
    }
  }

  return $element;
}

/**
 * Traducciones que hay que agregar en traducir interfaz [/admin/config/regional/translate/translate]
 *  ALT:   Pie de foto | Descripción
 *         Un pie de foto o descripción para esta imagen. Este valor podría ser utilizado para el SEO u otros widgets y no puede ser mayor de 500 caracteres.
 *  TITLE: Autoría | Derechos
 *         La autoría o derechos de autor de esta imagen. Este valor podría ser utilizado para el SEO o otros widgets y no puede ser mayor que 500 caracteres. El valor por defecto <em> Especial </ em>
 */

