<?php
/**
 * Implements hook_permisson().
 */
function suplementorsvp_permission() {
  $permissions['administer suplementorsvp settings'] = array(
    'title' => t('Administer suplementorsvp settings.'),
    'restrict access' => TRUE,
  );
  return $permissions;
}
function suplementorsvp_help($path, $arg) {
  if ($path == 'admin/help#suplementorsvp') {
    return t('Módulo para configuración del suplemento digital de RSVP');
  }
}
/**
 * Implements hook_menu().
 */
function suplementorsvp_menu() {
  $items=array();
  
  $items['admin/config/user-interface/suplementorsvp'] = array(
    'title'            => t('Suplemento RSVP'),
    'description'      => t('Configuración del suplemento digital de R.S.V.P.'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('suplementorsvp_admin_settings_form'),
    'access arguments' => array('administer suplementorsvp settings'),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'suplementorsvp.admin.inc',
  );
  return $items;
}
/**
 * Implements hook_block_info().
 */
function suplementorsvp_block_info() {
  return array(
    'suplementorsvp_sidebar_block' => array(
      'info'  => t('Suplemento RSVP 300'),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => "<front>\ntaxonomy/term/*",
    ),
  );
}
/**
 * Implements hook_block_view().
 */
function suplementorsvp_block_view($delta = '') {
  switch ($delta) {
    /*Content Left*/
    case 'suplementorsvp_sidebar_block':
      $block = array(
        'content' => _suplementorsvp_sidebar_block(),
      );
    break;
  }
  return $block;
}

function _suplementorsvp_sidebar_block(){
  drupal_add_css(drupal_get_path('module', 'suplementorsvp').'/suplementorsvp.css');
  $item=_get_item_suplemento_api();
  return '
<div class="suplementoDigital heraBig colorLink">
  <div class="globoWrapper centertext"><span class="heraBig">'.$item['title'].'</span></div>
  <div class="suplementoImage">
    <a target="_blank" href="'.$item['url'].'">
      <img alt="'.$item['image']['alt'].'" src="'.$item['image']['src'].'" class="'.$item['image']['effect'].'">
    </a>
  </div>
</div>
  ';
}
function _get_item_suplemento_api(){
  $data=_search_cache('suplementorsvp');
  if(!isset($data) || empty($data)){
    suplementorsvp_get_data();
    $data=_search_cache('suplementorsvp');
  }
  
  return $data;
}

/**
 * Implementation of hook_cron().
 */
function suplementorsvp_cron($config=array()) {
  if(!$config)
    $config=array();
  
  $today=time();
  /**
   * This cronjob must have executed every 30 minutes only on Fridays from 6 to 9 am CDT
   * [0/30       6-9        *           *           5     wget -O - -q -t 1 http://{domain_name}/imx_financial_indicators/cron] 
   */
  //Check if hour is les than 20 hours to let him pass
  
  $hour=date('H');
  $dayweek=date('w');
  if(($hour<10 && $hour>5) && ($dayweek=5)){
    suplementorsvp_get_data();
  }
}

function suplementorsvp_get_data(){
  /*
   * Leer y guardar en local path: /var/www/html/rsvpd7/files/rsvp/images/suplementos
   * Despues hacer la imagen derivada es sencilla solo hay que ajustar la url
   *  
  http://www.excelsior.com.mx/media/suplementos/Rsvp/RS140530_001W.jpg
  http://rsvpd7.jediteam.mx/files/rsvp/styles/large/public/images/suplementos/RS140530_001W.jpg
  */

  $items=file_get_contents('http://api.inventmx.com/v1/excelsior/complementos.json/3a5877fc16b6fcbf8eedbe55d091938a?type=suplemento&seccion=Rsvp');
  $items=json_decode($items);
  foreach($items->data as $item){
    if($item->seccion=='Rsvp'){
      $urlImage=$item->pages->mediums[0];
      $contentUrlImage=file_get_contents($urlImage);
      $filenameImage=explode('/',$urlImage);
      $filename=$filenameImage[6];
      $filenameImage=suplementorsvp_get_path().$filenameImage[6];
      $result=@file_put_contents($filenameImage, $contentUrlImage);
      $data=array(
        'title' => ucwords($item->type),
        'url'   => $item->url,
        'image' => array(
          'src' => url('files/rsvp/styles/large/public/images/suplementos/'.$filename, array('absolute'=>true)),
          'alt' => 'Suplemento digital de R.S.V.P.',
          'effect' => 'grow-rotate',
        ),
      );
      _create_cache('suplementorsvp',$data);
    }
  }
}

function suplementorsvp_get_path(){
  return DRUPAL_ROOT.'/'.variable_get('file_public_path','').'/images/suplementos/';
}
