<?php
/**
 * Implements hook_permisson().
 */
function digiteka_permission() {
  $permissions['administer digiteka settings'] = array(
    'title' => t('Administer Digiteka settings.'),
    'restrict access' => TRUE,
  );
  return $permissions;
}
/**
 * Implements hook_help
 */
function digiteka_help($path, $arg) {
  if ($path == 'admin/help#digiteka') {
    return t('Módulo para configuración de Digiteka');
  }
}

/**
 * Implements hook_menu().
 */
function digiteka_menu() {
  $items=array();
  $themekeyName=NULL;

  $items['admin/config/system/digiteka'] = array(
    'title'            => t('Digiteka Settings'),
    'description'      => t('Configure settings for Digiteka'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('digiteka_admin_settings_form'),
    'access arguments' => array('administer digiteka settings'),
    'access callback'  => 'user_access',
    'file'             => 'digiteka.admin.inc',
  );
  $items['admin/config/system/digiteka/default'] = array(
    'title'  => t('Digiteka Settings'),
    'type'   => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );

  /** Parche para Adrenalina */
  if(function_exists('themekey_is_active') && is_callable('themekey_is_active')){
    $themekeyName=' Adrenalina';
    $items['admin/config/system/digiteka/adrenalina'] = array(
      'title'            => t('Digiteka Settings'.$themekeyName),
      'description'      => t('Configure settings for Digiteka'.$themekeyName),
      'page callback'    => 'drupal_get_form',
      'page arguments'   => array('digiteka_admin_settings_form'),
      'access arguments' => array('administer digiteka settings'),
      'access callback'  => 'user_access',
      'type'             => MENU_LOCAL_TASK,
      'file'             => 'digiteka.admin.inc',
      'weight'           => 1,
    );
  }
  return $items;
}

/**
 * Implements block info.
 */
function digiteka_block_info() {

  $blocks['digiteka_node_block']=array(
    'info'  => t('Digiteka Node Block'),
    'cache'  => DRUPAL_CACHE_GLOBAL,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'node/*',
  );

  if(function_exists('themekey_is_active') && is_callable('themekey_is_active')){
    $themekeyName=' Adrenalina';
    $blockThemeKeyName='_adrenalina';
    $blocks['digiteka_node_block'.$blockThemeKeyName]=array(
      'info'  => t('Digiteka Node Block'.$themekeyName),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'node/*',
    );
  }

  return $blocks;
}
/**
 * Implements hook_block_view().
 */
function digiteka_block_view($delta = '') {
  switch ($delta) {
    /*Content Left*/
    case 'digiteka_node_block':
      $block = array(
        'content' => _digiteka_node_block(),
      );
    break;
    case 'digiteka_node_block_adrenalina':
      $block = array(
        'content' => _digiteka_node_block('adrenalina'),
      );
    break;
  }
  return $block;
}

function _digiteka_node_block($themekey=NULL){
  $variables=get_digiteka_variables($themekey);
  $status=$variables['status'];
  if(arg(0)=='node' && $status && !drupal_is_front_page()){
    $node=node_load(arg(1));
    $settings=$variables['settings'];
    $settings['zone']=isset($settings['zone']) && (!empty($settings['zone']) || $settings['zone']!='0') ? 'var ULTIMEDIA_zone = "'.$settings['zone'].'";' : '';
    $settings['date']=isset($settings['date']) ? date('Ymd',$node->{$settings['date']}) : date('Ymd');
    $settings['async']=isset($settings['async']) && !empty($settings['async']) ? 'true' : 'false';
    $settings['resize']=isset($settings['resize']) && !empty($settings['resize']) ? 'true' : 'false';


    return $settings['title'].'
<script type="text/javascript">
var ULTIMEDIA_mdtk   = "'.$settings['mdtk'].'";
'.$settings['zone'].'
var ULTIMEDIA_target = "'.$settings['target'].'";
var ULTIMEDIA_date   = "'.$settings['date'].'";
var ULTIMEDIA_async  = '.$settings['async'].';
var ULTIMEDIA_resize = '.$settings['resize'].';
</script>
<script type="text/javascript" src="http://www.ultimedia.com/js/common/smart.js"></script>';

  }
  return null; 
}

function get_digiteka_variables($themekey){
  if(!isset($themekey) || empty($themekey)){
    $themekey=NULL;
  }
  $path=arg(0);
  if($path=='adrenalina' || $themekey=='adrenalina'){
    return array(
      'status' => variable_get('digiteka_status_adrenalina',FALSE),
      'settings' => variable_get('digiteka_settings_adrenalina',FALSE),
    );
  }else{
    return array(
      'status' => variable_get('digiteka_status',FALSE),
    'settings' => variable_get('digiteka_settings',FALSE),
    );
  }
}
