<?php
/**
 * @file
 * Installation file for Zedo Integration.
 */

/**
 * Implements hook_install().
 */
function localddi_install() {
  variable_set('localddi_status',FALSE);
  variable_set('localddi_debug',FALSE);
  variable_set('localddi_wrapper','localddi-wrapper');
}

/**
 * Implements hook_uninstall().
 */
function localddi_uninstall() {
  #Delete all variables
  variable_del('localddi_status');
  variable_del('localddi_debug');
  variable_del('localddi_wrapper');
}
