<?php
/**
 * Implements hook_permisson().
 */
function localddi_permission() {
  $permissions['jediteam admin settings'] = array(
    'title' => t('JediTeam Admin settings.'),
    'restrict access' => TRUE,
  );
  return $permissions;
}
function localddi_help($path, $arg) {
  if ($path == 'admin/help#localddi') {
    return t('Módulo para configuración de Zedo');
  }
}
/**
 * Implements hook_menu().
 */
function localddi_menu() {
  $items=array();
  
  $items['admin/config/system/localddi'] = array(
    'title'            => t('Zedo settings'),
    'description'      => t('Configure settings for Zedo'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('localddi_admin_settings_form'),
    'access arguments' => array('jediteam admin settings'),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'localddi.admin.inc',
  );
  return $items;
}

function localddi_init(){
  $statusZedo=variable_get('localddi_status',FALSE);
  if(arg(0)=='node' && $statusZedo){
    $node=node_load(arg(1));
    if($node->type=='article'){
      $wrapperZedo=variable_get('localddi_wrapper','localddi-wrapper');
      $debugModeZedo=variable_get('localddi_debug',FALSE);
      if($debugModeZedo){
        //Debug mode
        $footerJS='var zflag_parent="'.$wrapperZedo.'";
var zflag_nid="2264";
var zflag_cid="1534";
var zflag_sid="0";
var zflag_sz="85";
var zflag_vast_domain="http://xp1.localddi.com/";
var zflag_width="1";
var zflag_height="1";';
        drupal_add_js($footerJS, array('type' => 'inline', 'scope' => 'footer', 'weight' => 98));
        drupal_add_js('http://c1.localddi.com/jsc/c1/frd.js', array('type' => 'external', 'scope' => 'footer', 'weight' => 99));
      }else{
        $footerJS='var zflag_parent="'.$wrapperZedo.'";
var zflag_nid="2870";
var zflag_cid="1";
var zflag_sid="1";
var zflag_sz="85";
var zflag_vast_domain="http://xp1.localddi.com/";
var zflag_width="1";
var zflag_height="1";
var zflag_bchan="2";';
        drupal_add_js($footerJS, array('type' => 'inline', 'scope' => 'footer', 'weight' => 98));
        drupal_add_js('http://e2.localddi.com/jsc/e2/frd.js', array('type' => 'external', 'scope' => 'footer', 'weight' => 99));
      }
      drupal_add_css(drupal_get_path('module', 'localddi').'/localddi.css');
    }
  }
}
