<?php
/**
 * Implements hook_permisson().
 */
function ovni_permission() {
  $permissions['administer ovni settings'] = array(
    'title' => t('Administer OVNI settings.'),
    'restrict access' => TRUE,
  );
  return $permissions;
}

/**
 * Implements template_preprocess_node().
 */
function ovni_preprocess_node(&$variables){
  $node=$variables['node'];
  if($node->type=='article'){
    $body=field_get_items('node', $node, 'body', $langcode = NULL);
    $view=field_view_value('node', $node, 'body', $body[0]);
    $searchBody=_search_youtube($view['#markup']);
    $variables['node']->body[LANGUAGE_NONE][0]['safe_value']=$searchBody;
  }
}

function _search_youtube($body){
  //$pattern="/\/\/[a-zA-X]+\.you[a-zA-Z0-9\.]+\/[a-zA-Z0-9]+\/[a-zA-Z0-9]+\?[a-zA-Z0-9-_\.:;=&]+/i";
  $pattern="/\/\/[a-zA-Z]+\.you[a-zA-Z0-9\.]+\/[a-zA-Z0-9]+\/[a-zA-Z0-9]+[\?a-zA-Z0-9-_\.:;=&]+/i";
  if(preg_match_all($pattern,$body)){
    //Playlist
    //<iframe width="560" height="315" src="//www.youtube.com/embed/NfKWsBH7SU8?list=PL6ETbF2qcS6XI-wRePP0n2bWSNMIKT5Uf" frameborder="0" allowfullscreen></iframe>
    //http://youtu.be/NfKWsBH7SU8?list=PL6ETbF2qcS6XI-wRePP0n2bWSNMIKT5Uf
    //Video standalone
    //http://youtu.be/w-YFKlqJfbE
    //<iframe width="560" height="315" src="//www.youtube.com/embed/w-YFKlqJfbE" frameborder="0" allowfullscreen></iframe>
    return preg_replace("/youtube.com/","youtube.be",$body);
  }
  return $body;
}
/**
 * Implements hook_help().
 */
function ovni_help($path, $arg) {
  if ($path == 'admin/help#ovni') {
    return t('Módulo para configuración de OVNI');
  }
}
/**
 * Implements hook_menu().
 */
function ovni_menu() {
  $items=array();
  $items['admin/config/system/ovni'] = array(
    'title'            => t('OVNI Integration'),
    'description'      => t('Manage, administration, configuration and others for OVNI Integration Module'),
    'page callback'    => 'ovni_admin_actions',
    'page arguments'   => array('manage'),
    'access arguments' => array('administer ovni settings'),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'ovni.admin.inc',
  );
  $items['admin/config/system/ovni/manage'] = array(
    'title'            => t('Administration'),
    'description'      => t('Manage, administration, configuration and others for OVNI Integration Module'),
    'page callback'    => 'ovni_admin_actions',
    'page arguments'   => array(4),
    'access arguments' => array('administer ovni settings'),
    'type'             => MENU_DEFAULT_LOCAL_TASK,
    'file'             => 'ovni.admin.inc',
    'weight'           => 1,
  );
  $items['admin/config/system/ovni/tasks'] = array(
    'title'            => t('Tasks'),
    'description'      => t('Configure tasks for OVNI Integration'),
    'page callback'    => 'ovni_admin_actions',
    'page arguments'   => array(4),
    'access arguments' => array('administer ovni settings'),
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'ovni.admin.inc',
    'weight'           => 2,
  );
  $items['admin/config/system/ovni/cache'] = array(
    'title'            => t('Cache'),
    'description'      => t('Configure cache for OVNI Integration'),
    'page callback'    => 'ovni_admin_actions',
    'page arguments'   => array(4),
    'access arguments' => array('administer ovni settings'),
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'ovni.admin.inc',
    'weight'           => 3,
  );
  $items['admin/config/system/ovni/api'] = array(
    'title'            => t('API'),
    'description'      => t('Configure API for OVNI Integration'),
    'page callback'    => 'ovni_admin_actions',
    'page arguments'   => array(4),
    'access arguments' => array('administer ovni settings'),
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'ovni.admin.inc',
    'weight'           => 4,
  );
  $items['admin/config/system/ovni/player'] = array(
    'title'            => t('Player'),
    'description'      => t('Configure Player for OVNI'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('ovni_player_admin_settings_form'),
    'access arguments' => array('administer ovni settings'),
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'ovni.admin.inc',
    'weight'           => 5,
  );
  $items['admin/config/system/ovni/settings'] = array(
    'title'            => t('Configuration'),
    'description'      => t('Configure settings for OVNI'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('ovni_admin_settings_form'),
    'access arguments' => array('administer ovni settings'),
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'ovni.admin.inc',
    'weight'           => 5,
  );
  return $items;
}
/**
 * Implements hook_cron().
 */
function hook_cron() {
  // Short-running operation example, not using a queue:
  // Delete all expired records since the last cron run.
  $expires = variable_get('ovni_cron_last_run', REQUEST_TIME);
  db_delete('mymodule_table')->condition('expires', $expires, '>=')->execute();
  variable_set('ovni_cron_last_run', REQUEST_TIME);

  // Long-running operation example, leveraging a queue:
  // Fetch feeds from other sites.
  $result = db_query('SELECT * FROM {aggregator_feed} WHERE checked + refresh < :time AND refresh <> :never', array(
    ':time' => REQUEST_TIME,
    ':never' => AGGREGATOR_CLEAR_NEVER,
  ));
  $queue = DrupalQueue::get('aggregator_feeds');
  foreach ($result as $feed) {
    $queue->createItem($feed);
  }
}
/**
 * Implements a callback from Google Drive
 * It use ZendGdata as Helper for do that
 * @see inc/zendgdata.inc for more info
 * @return array Channels from Google Doc Spreadsheet
 */
function get_channels() {
  //Search cache
  $filename = 'ovni_channels';
  $data = _search_cache($filename);
  if (!$data) {
    //Config Google Docs
    $config = array(
      'user' => 'webmaster@inventmx.com',
      'pass' => '$5ap1d3CV$',
      'shared' => array(
        'key' => '13NJALr3PGxO754kfDbQzrBGRvRCH8MMtP1FbH9CCtNk',
      ),
      'page' => 1,
    );
    //Load ZendGdata
    module_load_include('inc', 'ovni', 'inc/zendgdata');
    $data = zendGoogleApiData($config);
    _create_cache($filename, $data);
  }
  return $data;
}

/**
 * All of this information are recover from Youtube API Examples
 * https://www.googleapis.com/youtube/v3/channels?key=AIzaSyCALigkDh_38yvQclxGsArCFA9-4fZdlVg&part=id,snippet,brandingSettings,contentDetails,invideoPromotion,statistics,topicDetails&id=UCGrXKTp-j4Yoz48SIX9uwqg
 * https://www.googleapis.com/youtube/v3/search?key=AIzaSyCALigkDh_38yvQclxGsArCFA9-4fZdlVg&part=id,snippet&channelId=UCauNSMXhK-TRbICWfF1bAKA&order=date&maxResults=50&type=video
 * https://www.googleapis.com/youtube/v3/search?key=AIzaSyCALigkDh_38yvQclxGsArCFA9-4fZdlVg&part=snippet&channelId=UCauNSMXhK-TRbICWfF1bAKA&order=date&maxResults=50&type=video&pageToken=CDIQAA
 */
function ovni_youtube_channels(){
  /**
   * https://www.googleapis.com/youtube/v3/channels?key=AIzaSyCALigkDh_38yvQclxGsArCFA9-4fZdlVg&part=id,snippet,statistics&id=UCGrXKTp-j4Yoz48SIX9uwqg
   */
}
function ovni_get_videos(){
  /**
   * https://www.googleapis.com/youtube/v3/search?key=AIzaSyCALigkDh_38yvQclxGsArCFA9-4fZdlVg&part=id,snippet&channelId=UCauNSMXhK-TRbICWfF1bAKA&order=date&maxResults=50&type=video
   */
}
function ovni_get_info_video(){
  /**
   * https://www.googleapis.com/youtube/v3/videos?key=AIzaSyCALigkDh_38yvQclxGsArCFA9-4fZdlVg&part=snippet&id=z3LlFWwDKew
   */
}
function ovni_get_playlists(){
  /**
   * https://www.googleapis.com/youtube/v3/playlists?key=AIzaSyCALigkDh_38yvQclxGsArCFA9-4fZdlVg&part=id,snippet,status&channelId=UCauNSMXhK-TRbICWfF1bAKA
   */
}
function ovni_get_playlist_items(){
  /**
   * https://www.googleapis.com/youtube/v3/playlistItems?key=AIzaSyCALigkDh_38yvQclxGsArCFA9-4fZdlVg&part=id,snippet,contentDetails,status&maxResults=10&playlistId=PLhT_v6tL99kkC1tdJQd1znxbp9dhTQAjy
   */
}
