<?php
function gimrh_embed_menu() {
  $items=array();
  $items['bolsa-de-trabajo'] = array(
    'title'            => 'Trabaja con nosotros',
    'page callback'    => 'gimrh_embed_html',
    'access callback'  => TRUE,
    'type'             => MENU_CALLBACK,
  );
  return $items;
}

function gimrh_embed_html(){
  //Add X-Frame-Options
  $xframe_metas[] = array(
    '#tag' => 'meta',
    '#attributes' => array(
      'about' => url('taxonomy/term/' . $term->tid),
      'typeof' => $term->rdf_mapping['rdftype'],
      'property' => $term->rdf_mapping['name']['predicates'],
      'content' => $term->name,
    ),
  );
  drupal_add_html_head($data,'meta-xframe-gimrh');
return '
<script type="text/javascript">
var eventMethod = window.addEventListener ? "addEventListener" : "attachEvent";
var eventer = window[eventMethod];
var messageEvent = eventMethod == "attachEvent" ? "onmessage" : "message";
// Listen to message from child window
eventer(messageEvent,function(e) {
  if(e.origin == "http://local.invent.mx"){
    console.log("Parent received message: ", e.data.action);
    console.log("Origin: ", e.origin);
    console.log("Source: ", e.source);
    if(e.data.action=="submit"){
      window.scrollTo(0,0);
    }
  }
},false);
</script>
<iframe id="gimrh-work-with-us" width="100%" height="2280" frameborder="0" src="http://local.invent.mx/bolsa-de-trabajo" scrolling="no" onload="scroll(0,0);"></iframe>
';
}