<?php
include_once(drupal_get_path('module', 'imx_rsvp_home').'/imx_rsvp_home.pages.inc');
/**
 * Implements hook_block_info().
 */

function imx_rsvp_home_init(){
  if(drupal_is_front_page()){
    drupal_add_css(drupal_get_path('module', 'imx_rsvp_home').'/imx_rsvp_home.css');
    drupal_add_css(drupal_get_path('module', 'imx_rsvp_home').'/home.css');
  }
} 
function imx_rsvp_home_block_info() {
  return array(
    /*Content Left*/
    'hf_small_default_1' => array(
      'info'  => t('Home Flujo Small 1'),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
    'hf_small_default_2' => array(
      'info'  => t('Home Flujo Small 2'),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
    'hf_small_default_3' => array(
      'info'  => t('Home Flujo Small 3'),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
    /*Content wide*/
    'home_block_flow_wide_1' => array(
      'info'  => t('Flujo Home Ancho Completo 1'),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
    'home_block_flow_wide_2' => array(
      'info'  => t('Flujo Home Ancho Completo 2'),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
    'home_block_flow_wide_3' => array(
      'info'  => t('Flujo Home Ancho Completo 3'),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
    'home_block_flow_wide_4' => array(
      'info'  => t('Flujo Home Ancho Completo 4'),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
    'home_block_flow_wide_5' => array(
      'info'  => t('Flujo Home Ancho Completo 5'),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
    'home_block_flow_wide_6' => array(
      'info'  => t('Flujo Home Ancho Completo 6'),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
    'home_block_phrase' => array(
      'info'  => t('Frase célebre'),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
    'home_block_rsvp_grid_iwant' => array(
      'info'  => t('Cuadricula Lo quiero'),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
    'home_block_rsvp_grid_special' => array(
      'info'  => t('Cuadricula Especial'),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
    'home_block_rsvp_grid_columns' => array(
      'info'  => t('Cuadricula Columnas'),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
    'home_block_rsvp_grid_profile' => array(
      'info'  => t('Cuadricula Perfiles'),
      'cache'  => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
  );
}
/**
 * Implements hook_block_view().
 */
function imx_rsvp_home_block_view($delta = '') {
  $block=NULL;
  switch ($delta) {
    /*Content Left*/
    case 'hf_small_default_1':
      $block = array(
        'subject' => t('Home Flujo Small 1'),
        'content' => _get_html_rsvp_home($delta,0,1),
      );
    break;
    case 'hf_small_default_2':
      $block = array(
        'subject' => t('Home Flujo Small 2'),
        'content' => _get_html_rsvp_home($delta,3,3),
      );
    break;
    case 'hf_small_default_3':
      $block = array(
        'subject' => t('Home Flujo Small 3'),
        'content' => _get_html_rsvp_home($delta,6,3),
      );
    break;
    
    /*Content wide*/
    case 'home_block_flow_wide_1':
      $block = array(
        'subject' => t('Flujo Home Ancho Completo 1'),
        'content' => _get_html_rsvp_home($delta,3,3),
      );
    break;
    case 'home_block_flow_wide_2':
      $block = array(
        'subject' => t('Flujo Home Ancho Completo 2'),
        'content' => _get_html_rsvp_home($delta,6,3),
      );
    break;
    case 'home_block_flow_wide_3':
      $block = array(
        'subject' => t('Flujo Home Ancho Completo 3'),
        'content' => _get_html_rsvp_home($delta,9,3),
      );
    break;
    case 'home_block_flow_wide_4':
      $block = array(
        'subject' => t('Flujo Home Ancho Completo 4'),
        'content' => _get_html_rsvp_home($delta,12,3),
      );
    break;
    case 'home_block_flow_wide_5':
      $block = array(
        'subject' => t('Flujo Home Ancho Completo 5'),
        'content' => _get_html_rsvp_home($delta,15,3),
      );
    break;
    case 'home_block_flow_wide_6':
      $block = array(
        'subject' => t('Flujo Home Ancho Completo 6'),
        'content' => _get_html_rsvp_home($delta,18,12),
      );
    break;
    
    case 'home_block_phrase':
      $block = array(
        'subject' => t('Frase célebre'),
        'content' => _get_html_rsvp_phrase(),
      );
    break;
    
    /*********************************************************************/
    case 'home_block_rsvp_grid_iwant':
      $block = array(
        'subject' => t('Cuadricula Lo quiero'),
        'content' => _get_rsvp_block_style('rsvp_grid_iwant','block_3',0,6),
      );
    break;
    case 'home_block_rsvp_grid_special':
      $block = array(
        'subject' => t('Cuadricula Especial'),
        'content' => _get_rsvp_block_style('rsvp_grid_special','block_1',0,4),
      );
    break;
    case 'home_block_rsvp_grid_columns':
      $block = array(
        'subject' => t('Cuadricula Columnas'),
        'content' => _get_rsvp_block_style('rsvp_grid_columns','block_2',0,4),
      );
    break;
    case 'home_block_rsvp_grid_profile':
      $block = array(
        'subject' => t('Cuadricula Perfiles'),
        'content' => _get_rsvp_block_style('rsvp_grid_profile','block_2',0,10),
      );
    break;
  }
  return $block;
}
function _get_html_rsvp_home($delta='',$offset,$limit){
  $items=_get_home_items_list('frontpage','block_1',$offset,$limit);
  $html=array();
  
  if(preg_match('{small}', $delta)){
    //Styles
    foreach($items as $item){
      $found_style=_search_rsvp_home_style($item['style_small']);
      #var_dump('<pre>');var_dump($item);var_dump($found_style);var_dump('</pre>');
      if($found_style){
        $html[]=call_user_func($item['style_small'],$item);
      }
    }
  }else{
    foreach($items as $item){
      $found_style=_search_rsvp_home_style($item['style_wide']);
      #var_dump('<pre>');var_dump($item);var_dump($found_style);var_dump('</pre>');
      if($found_style){
        $html[]=call_user_func($item['style_wide'],$item);
      }
    }
  }
  return implode('',$html);
}

function _get_rsvp_block_style($style,$display_id,$offset,$limit){
  $view_name='nodequeue_5';
  if($style=='rsvp_grid_profile' || $style=='rsvp_grid_iwant'){
    //Taxonomy view
    $view_name='otras_notas';
  }
  $items=_get_home_items_list($view_name,$display_id,$offset,$limit);
  return call_user_func($style,$items);
}

function _get_home_items_list($view_name, $display_id='default',$offset,$limit){
  if (!$view_name)
    return NULL;
  $view=views_get_view($view_name, $display_id);
  $view->set_offset($offset);
  $view->set_items_per_page($limit);
  $view->preview($display_id);
  $view=$view->result;
  $items=array();
  foreach ($view as $node) {
    $items[]=array(
      'title'   => $node->node_title,
      'canal'   => isset($node->field_field_canal[0]['rendered']['#markup']) ? $node->field_field_canal[0]['rendered']['#markup'] : NULL,
      'summary' => _get_item_summary($node),
      'image'   => array(
        'fid'   => isset($node->field_field_portada[0]['rendered']['#item']['fid']) ? $node->field_field_portada[0]['rendered']['#item']['fid'] : NULL,
        'name'  => isset($node->field_field_portada[0]['rendered']['#item']['filename']) ? $node->field_field_portada[0]['rendered']['#item']['filename'] : NULL,
        'uri'   => isset($node->field_field_portada[0]['rendered']['#item']['uri']) ? $node->field_field_portada[0]['rendered']['#item']['uri'] : NULL,
        'alt'   => isset($node->field_field_portada[0]['rendered']['#item']['alt']) ? $node->field_field_portada[0]['rendered']['#item']['alt'] : NULL,
        'title' => isset($node->field_field_portada[0]['rendered']['#item']['alt']) ? $node->field_field_portada[0]['rendered']['#item']['alt'] : NULL,
        'width' => isset($node->field_field_portada[0]['rendered']['#item']['width']) ? $node->field_field_portada[0]['rendered']['#item']['width'] : NULL,
        'height'=> isset($node->field_field_portada[0]['rendered']['#item']['height']) ? $node->field_field_portada[0]['rendered']['#item']['height'] : NULL,
        'style' => isset($node->field_field_portada[0]['rendered']['#image_style']) ? $node->field_field_portada[0]['rendered']['#image_style'] : NULL,
      ),
      'style_wide'  => isset($node->field_field_style_wide[0]['rendered']['#markup']) ? $node->field_field_style_wide[0]['rendered']['#markup'] : NULL,
      'style_small' => isset($node->field_field_style_small[0]['rendered']['#markup']) ? $node->field_field_style_small[0]['rendered']['#markup'] : NULL,
      'path'    => isset($node->field_field_portada[0]['rendered']['#path']['path']) ? $node->field_field_portada[0]['rendered']['#path']['path'] : NULL,
    );
  }
  return $items;
}

function _get_item_summary($node){
  if(!$node){
    return null;
  }
  $summary=isset($node->field_body[0]['rendered']['#markup']) ? $node->field_body[0]['rendered']['#markup'] : NULL;
  $summary=trim(strip_tags($summary));
  
  //Summary exists
  if(isset($summary) && !empty($summary)){
    return $summary;
  }else if(isset($node->node_type) && $node->node_type=='gallerie'){
    return isset($node->field_field_portada[0]['rendered']['#item']['alt']) ? $node->field_field_portada[0]['rendered']['#item']['alt'] : NULL;
  }
  
  return null;
}

/**
 * Hook node_insert
 */
function imx_rsvp_home_node_insert($node){
  if($node->type=='phrase' && $node->status==1){
    cache_clear_all('last_item_phrase', 'cache'); 
  }
}
/**
 * Hook node_update
 */
function imx_rsvp_home_node_update($node){
  if($node->type=='phrase' && $node->status==1){
    cache_clear_all('last_item_phrase', 'cache'); 
  }
}

function _search_rsvp_home_style($key){
  $search=_get_rsvp_styles_names();
  $found=array_key_exists($key, $search);
  if($found){
    return true;
  }
  return false;
}

function _get_rsvp_styles_names(){
  return array (
    'hf_small_default'          => 'Default corto',
    'hf_wide_default'           => 'Default largo',
    'hf_small_ribbon_boda'      => 'Listón Boda Corto',
    'hf_wide_ribbon_boda'       => 'Listón Boda Largo',
    'hf_wide_ribbon_loquiero'   => 'Listón Lo quiero Largo',
    'hf_wide_ribbon_bombon'     => 'Listón Bombón Largo',
    'hf_wide_ribbon_socialspot' => 'Listón Socialspot Largo',
    'hf_wide_profile'           => 'Perfiles largo',
    'hf_wide_background'        => 'Imagen de fondo largo',
    
    'rsvp_promoted_common' => 'Promocionado',
    'rsvp_promoted_wedding' => 'Promocionado Boda',
    'rsvp_promoted_iwant' => 'Promocionado Lo quiero',
    'rsvp_promoted_profile' => 'Promocionado Perfiles',
    'rsvp_outstanding_common' => 'Destacado',
    'rsvp_outstanding_wedding' => 'Destacado Boda',
    'rsvp_outstanding_iwant' => 'Destacado Lo quiero',
    'rsvp_outstanding_profile' => 'Destacado Perfiles',
    'rsvp_tile_common' => 'Mosaico',
    'rsvp_tile_wedding' => 'Mosaico Boda',
    'rsvp_tile_iwant' => 'Mosaico Lo quiero',
    'rsvp_tile_profile' => 'Mosaico Perfiles',
    'rsvp_grid_common' => 'Cuadrícula',
    'rsvp_grid_wedding' => 'Cuadrícula Boda',
    'rsvp_grid_iwant' => 'Cuadrícula Lo quiero',
    'rsvp_grid_profile' => 'Cuadrícula Perfiles',
    'rsvp_columns_common' => 'Columnas',
    'rsvp_columns_wedding' => 'Columnas Boda',
    'rsvp_columns_iwant' => 'Columnas Lo quiero',
    'rsvp_columns_profile' => 'Columnas Perfiles',
    'rsvp_banner_common' => 'Pendones',
    'rsvp_banner_wedding' => 'Pendones Boda',
    'rsvp_banner_iwant' => 'Pendones Lo quiero',
    'rsvp_banner_profile' => 'Pendones Perfiles',
    'rsvp_banner_socialspot' => 'Pendones Socialspot',
    'rsvp_background_common' => 'Imagen de fondo',
    'rsvp_background_wedding' => 'Imagen de fondo Boda',
    'rsvp_background_iwant' => 'Imagen de fondo Lo quiero',
    'rsvp_background_profile' => 'Imagen de fondo Perfiles',
    'rsvp_awesome_common' => 'Impresionante',
    'rsvp_awesome_wedding' => 'Impresionante Boda',
    'rsvp_awesome_iwant' => 'Impresionante Lo quiero',
    'rsvp_awesome_profile' => 'Impresionante Perfiles',
  );
}

function rsvp_promoted_iwant($item=null){}
function rsvp_outstanding_common($item=null){}
function rsvp_outstanding_wedding($item=null){}
function rsvp_outstanding_iwant($item=null){}
function rsvp_outstanding_profile($item=null){}
function rsvp_tile_common($item=null){}
function rsvp_tile_wedding($item=null){}
function rsvp_tile_iwant($item=null){}
function rsvp_tile_profile($item=null){}
function rsvp_grid_common($item=null){}
function rsvp_grid_wedding($item=null){}
function rsvp_columns_common($item=null){}
function rsvp_columns_wedding($item=null){}
function rsvp_columns_iwant($item=null){}
function rsvp_columns_profile($item=null){}
function rsvp_banner_common($item=null){}
function rsvp_banner_wedding($item=null){}
function rsvp_banner_iwant($item=null){}
function rsvp_banner_profile($item=null){}
function rsvp_banner_socialspot($item=null){}
function rsvp_background_common($item=null){}
function rsvp_background_wedding($item=null){}
function rsvp_background_iwant($item=null){}
function rsvp_background_profile($item=null){}
function rsvp_awesome_common($item=null){}
function rsvp_awesome_profile($item=null){}
